### ISSUE TITLE
Detectar idioma en el nombre del archivo

### ISSUE THREAD

**Issue by brandongallardoa** [YerkoPalma/pangea#2]
Ademas de seleccionar el idioma en el select se puede detectar el idioma de la imagen en el nombre del archivo. Esto sería de manera opcional y si no se indica uno se procede de la manera normal.
En este caso solo propongo detectar poniendo un sufijo en el nombre.

Ejemplos de detectar el idioma en el nombre utilizando un sufijo:
```
Nombre de archivo -es.png
nombre-de-archivo-es.png
nombre de - archivo -es.png
asdas-es.png
Nombre-de archivo  -es.png
[cualquier carácter].png
```
La idea es que se podría en teoría poner cualquier nombre incluso muchos guiones y si no hay ninguno entonces se asume que no se especifico el idioma.

Ejemplo de como se podría obtendría el sufijo:

```
loadImage (event) {
    // resto del código omitido
 
    var filename = file.name;
    
   if (filename.indexOf('-') > -1) {
        var nameWithoutExt = filename.substring(0, filename.indexOf('.')) // quitamos la extensión
        var splittedFilename = nameWithoutExt.split("-");
        var suffix = splittedFilename[splittedFilename.length - 1]
        console.log(suffix)
    }

    // resto del código omitido
  }
```

**Comment by YerkoPalma** [comment]
Puedes mandar un PR con el cambio si quieres 😉 

Ten en cuenta que solo afectara a dispositivos de escritorio, ya que en móviles por defecto se abre la cámara para tomar una foto y usar esa como archivo.

**Comment by Brandonxy** [comment]
> Ademas de seleccionar el idioma en el select se puede detectar el idioma de la imagen en el nombre del archivo. Esto sería de manera opcional y si no se indica uno se procede de la manera normal.
> En este caso solo propongo detectar poniendo un sufijo en el nombre.
> 
> Ejemplos de detectar el idioma en el nombre utilizando un sufijo:
> 
> ```
> Nombre de archivo -es.png
> nombre-de-archivo-es.png
> nombre de - archivo -es.png
> asdas-es.png
> Nombre-de archivo  -es.png
> [cualquier carácter].png
> ```
> La idea es que se podría en teoría poner cualquier nombre incluso muchos guiones y si no hay ninguno entonces se asume que no se especifico el idioma.
> 
> Ejemplo de como se podría obtendría el sufijo:
> 
> ```
> loadImage (event) {
>     // resto del código omitido
>  
>     var filename = file.name;
>     
>    if (filename.indexOf('-') > -1) {
>         var nameWithoutExt = filename.substring(0, filename.indexOf('.')) // quitamos la extensión
>         var splittedFilename = nameWithoutExt.split("-");
>         var suffix = splittedFilename[splittedFilename.length - 1]
>         console.log(suffix)
>     }
> 
>     // resto del código omitido
>   }
> ```

**Comment by brandongallardoa** [comment]
Ahí esta el pull request #3

**Comment by YerkoPalma** [comment]
Gracias :)
